name: "Bug Report"
title: "[BUG] <title>"
description: A bug is a demonstrable problem that is caused by the code in the repository. Good bug reports are extremely helpful - thank you!
labels: ["🩸 BUG"]
assignees:
  - sirthxalot
body:
  - type: markdown
    attributes:
      value: |
        A good bug report shouldn't leave others needing to chase you up for more information. Please try to be as detailed as possible in your report. What is your environment? What steps will reproduce the issue? What browser(s) and OS experience the problem? What would you expect to be the outcome? All these details will help people to fix any potential bugs.

        ⚠️ If you think that you have found a security issue, don't use the issue tracker and don't publish it publicly. Read our [security advisory](../SECURITY.md) instead.
  - type: input
    id: affected-versions
    attributes:
      label: Version
      placeholder: x.y.z
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: |
        ⚠️This is the most important part of the report ⚠️
        Without a way to easily reproduce your issue, there is little chance we will be able to help you and work on a fix.
        Please, take the time to show us some code and/or config that is needed for others to reproduce the problem easily.
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: |
        Optional: only if you have suggestions on a fix/reason for the bug
        Don't hesitate to create a pull request with your solution, it helps get faster feedback.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Optional: any other context about the problem: log messages, screenshots, etc."
