title: "«your title goes here»"
name: "Bug Report"
description: "Report a demonstrable problem that is caused by the code in the repository."
labels: [":speak_no_evil: BUG"]
assignees:
  - "sirthxalot"
body:
  - type: input
    id: version
    attributes:
      label: "Version"
      description: "Which version is affected?"
      placeholder: "x.y.z"
    validations:
      required: true
