title: "«your title goes here»"
name: "Report something that needs to be fixed."
description: "A bug is a demonstrable problem that is caused by the code in the repository. Good bug reports are extremely helpful - thank you!"
labels: ["🙊 BUG"]
assignees:
  - "sirthxalot"
body:
  - type: input
    id: version
    attributes:
      label: "Version"
      description: "The affected version of the software:"
      placeholder: "x.y.z"
    validations:
      required: true
