name: "Bug Report"
title: "[BUG] <title>"
description: File a bug report
labels: ["🩸 BUG"]
assignees:
  - sirthxalot
body:
  - type: markdown
    attributes:
      value: "Bugs are the worst!"
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
