  title: "Feature «your title goes here»"
  name: "Feature Request"
  description: "Extend or add new functionality to the source code."
  labels: ["🐧 FEATURE"]
  assignees:
    - "sirthxalot"
  body:
    - type: markdown
      attributes:
        value: |
          A feature is new functionality that has been added to the API. 
          The keyword is new, this means that you can now do something 
          that was not possible before. Often new features don't break 
          the backward compatibility which means that they can be 
          declared as minors.

          Enhancements on the other hand improve a current implementation 
          of the API. So they often affect the code in a way that makes it 
          backward incompatible. If that's the case a new major release must 
          be declared (depending on its gravity).

          **Warning**: Feature requests are welcome. But take a moment to find out 
          whether your idea fits with the scope and aims of the project. 
          It's up to you to make a strong case to convince the project's 
          developers of the merits of this feature. 

          Please provide as much detail and context as possible and start a 
          [discussion](./../discussions/categories/ideas) before creating the 
          ticket - thank you!
          
          ------------------------------------------------------------------------
    - type: input
      id: version
      attributes:
        label: "Version"
        description: "Which version is affected?"
        placeholder: "x.y.z"
      validations:
        required: true     
    
