name: "Request a new feature"
title: "[FEATURE] «title»"
description: "Feature requests are welcome. But take a moment to find out whether your idea fits with the scope and aims of the project."
labels: ["🔥 FEATURE"]
assignees:
  - sirthxalot
body:
  - type: markdown
    attributes:
      value: |
        > ❤️ We strongly recommend to begin a [discussion](./../discussions/) before open a ticket!
        > It's up to you to make a strong case to convince the project's developers of the merits of this feature.
        > Please provide as much detail and context as possible - thank you!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "A clear and concise description of the new feature"
    validations:
      required: true
  - type: textarea
    id: benefitors
    attributes:
      label: Benefitors
      description: "Optional: Who benefits of this feature? Where is the value?"
  - type: textarea
    id: example
    attributes:
      label: Example
      description: "Optional: An example of how the implementation may looks like?"
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Optional: any other context about the problem: log messages, screenshots, etc."
  - type: checkboxes
    id: code-impact
    attributes:
      label: "Code Impact"
      description: "Please check if its true"
      options:
        - label: "Breaks the backward compatibility"
        - label: "Causes code deprecations"
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: "Stuff you will need to do before submitting the issue."
      options:
        - label: "I agree to follow this project's [Code of Conduct](./../blob/main/.github/CODE_OF_CONDUCT.md)."
          required: true
        - label: "I have used the GitHub issue search to check if the issue has not been reported already."
          required: true
