title: "«your title goes here»"
name: "Documentation"
description: "Report some serious issues with the documentation, e.g. browser errors or lacks of information."
labels: ["documentation"]
assignees:
  - "sirthxalot"
body:
  - type: markdown
    attributes:
      value: |
        ## Introduction

        We take the documentation serious. It is important that we support our
        community with the necessary information and the maintainers give a lot
        of freedom to the contributors to explain themselves. This sometimes
        causes misunderstands or lacks of information that needs to be corrected.

        However please do not report some small things like a missing dot or a
        little misspelling as long as it does not disturbing you too much.

        Thank you!

        ## Report
  - type: input
    id: url
    attributes:
      label: "URL"
      description: "URL that leads to the documentation article:"
      placeholder: "https://sirthxalot.github.com/..."
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "A clear and concise description of the problem. What happend? And what do you expect to happen?"
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: "How to reproduce"
      description: |
        Optional: Without a way to easily reproduce your issue, there is little chance we will be able to help you and work on a fix.
        Please, take the time to show us some code and/or config that is needed for others to reproduce the problem easily.
    validations:
      required: false
  - type: textarea
    id: possible-solution
    attributes:
      label: "Possible Solution"
      description: |
        Optional: Only if you have suggestions on how the implementation may look like?
        Don't hesitate to create a pull request with your solution, it helps get faster feedback.
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Optional: Any other context you may want to share. Or any information about an environment that may causes trouble."
  - type: markdown
    attributes:
      value: "## Checklist"
  - type: checkboxes
    id: checklist
    attributes:
      label: "Agreements"
      options:
        - label: "I agree to follow the [code of conduct](./../blob/main/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)."
          required: true
        - label: "I agree to follow the [contribution guideline](./../blob/main/.github/CONTRIBUTING.md#introduction)."
          required: true
        - label: "I have used the [GitHub issue search](./../issues/?q=label%3A\"refactor\"+) to check if the issue has not been reported already."
          required: true
