blank_issues_enabled: true
contact_links:
  - name: Support Question
    url: https://github.com/sirthxalot/laravel-winterfell/dicussions/
    about: The issue trackers is not intended to provide help or support. Use GitHub discussions instead.

